version: "3"
services:
  dogovorapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7254:7254"
      - "5254:5254"
    container_name: "dogovor.api"
    networks:
      - dogovor-network
networks:
  dogovor-network:
    driver: bridge
