// <auto-generated />
using System;
using ConnectionProvider;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConnectionProvider.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entity.Entities.Citizenship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CitizenOf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("citizenships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CitizenOf = "шаҳрванди Ҷумҳурии Тоҷикистон"
                        });
                });

            modelBuilder.Entity("Entity.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityName = "г.Душанбе"
                        });
                });

            modelBuilder.Entity("Entity.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentName = "Отдел по работе с партнерами"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentName = "Отдел кадров"
                        });
                });

            modelBuilder.Entity("Entity.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfIssue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("cityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("cityId");

                    b.ToTable("documents");
                });

            modelBuilder.Entity("Entity.Entities.FormToFill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("documentId")
                        .HasColumnType("integer");

                    b.Property<int?>("principalInfoId")
                        .HasColumnType("integer");

                    b.Property<int?>("purposeId")
                        .HasColumnType("integer");

                    b.Property<int?>("receiversInfoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("validFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("validUntill")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("documentId");

                    b.HasIndex("principalInfoId");

                    b.HasIndex("purposeId");

                    b.HasIndex("receiversInfoId");

                    b.ToTable("formsToFill");
                });

            modelBuilder.Entity("Entity.Entities.PrincipalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PrincipalNameId")
                        .HasColumnType("integer");

                    b.Property<int>("PrincipalPlaceId")
                        .HasColumnType("integer");

                    b.Property<int>("PrincipalPositionId")
                        .HasColumnType("integer");

                    b.Property<int>("PrincipalReasonId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceiversAmount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalNameId");

                    b.HasIndex("PrincipalPlaceId");

                    b.HasIndex("PrincipalPositionId");

                    b.HasIndex("PrincipalReasonId");

                    b.ToTable("principalInfos");
                });

            modelBuilder.Entity("Entity.Entities.PrincipalName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PrincipalFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("principalNames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PrincipalFullName = "Курбонов Абдулло У."
                        });
                });

            modelBuilder.Entity("Entity.Entities.PrincipalPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PrincipalPlaceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("principalPlaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PrincipalPlaceName = "Ҷамъияти саҳомии кушодаи «Алиф Бонк»"
                        });
                });

            modelBuilder.Entity("Entity.Entities.PrincipalPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("principalPositions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PositionName = "Раис"
                        });
                });

            modelBuilder.Entity("Entity.Entities.PrincipalReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ReasonType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("principalReasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ReasonType = "Оиннома"
                        });
                });

            modelBuilder.Entity("Entity.Entities.Purpose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PurposeText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("purposes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PurposeText = "Салом, Оферта, ДБО, Банковский счет, Депозит"
                        },
                        new
                        {
                            Id = 2,
                            PurposeText = "СМИ, залог, поручительство"
                        },
                        new
                        {
                            Id = 3,
                            PurposeText = "Озод намудани амволи гарав"
                        });
                });

            modelBuilder.Entity("Entity.Entities.ReceiverInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PassportDateOfIssue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportPlaceOfIssue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiversFullname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReceiversPassportTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("СitizenshipId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReceiversPassportTypeId");

                    b.HasIndex("СitizenshipId");

                    b.ToTable("receiverInfos");
                });

            modelBuilder.Entity("Entity.Entities.ReceiversPassportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("receiversPassportTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "шиносномаи"
                        });
                });

            modelBuilder.Entity("Entity.Entities.ResetPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RandomNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ValidDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("resetPasswords");
                });

            modelBuilder.Entity("Entity.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Entity.Entities.Document", b =>
                {
                    b.HasOne("Entity.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("cityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Entity.Entities.FormToFill", b =>
                {
                    b.HasOne("Entity.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("documentId");

                    b.HasOne("Entity.Entities.PrincipalInfo", "PrincipalInfo")
                        .WithMany()
                        .HasForeignKey("principalInfoId");

                    b.HasOne("Entity.Entities.Purpose", "Purpose")
                        .WithMany()
                        .HasForeignKey("purposeId");

                    b.HasOne("Entity.Entities.ReceiverInfo", "ReceiversInfo")
                        .WithMany()
                        .HasForeignKey("receiversInfoId");

                    b.Navigation("Document");

                    b.Navigation("PrincipalInfo");

                    b.Navigation("Purpose");

                    b.Navigation("ReceiversInfo");
                });

            modelBuilder.Entity("Entity.Entities.PrincipalInfo", b =>
                {
                    b.HasOne("Entity.Entities.PrincipalName", "PrincipalName")
                        .WithMany()
                        .HasForeignKey("PrincipalNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Entities.PrincipalPlace", "PrincipalPlace")
                        .WithMany()
                        .HasForeignKey("PrincipalPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Entities.PrincipalPosition", "PrincipalPosition")
                        .WithMany()
                        .HasForeignKey("PrincipalPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Entities.PrincipalReason", "PrincipalReason")
                        .WithMany()
                        .HasForeignKey("PrincipalReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrincipalName");

                    b.Navigation("PrincipalPlace");

                    b.Navigation("PrincipalPosition");

                    b.Navigation("PrincipalReason");
                });

            modelBuilder.Entity("Entity.Entities.ReceiverInfo", b =>
                {
                    b.HasOne("Entity.Entities.ReceiversPassportType", "ReceiversPassportType")
                        .WithMany()
                        .HasForeignKey("ReceiversPassportTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Entities.Citizenship", "Citizenship")
                        .WithMany()
                        .HasForeignKey("СitizenshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizenship");

                    b.Navigation("ReceiversPassportType");
                });

            modelBuilder.Entity("Entity.Entities.ResetPassword", b =>
                {
                    b.HasOne("Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.HasOne("Entity.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
